// "use client"; if needed to use usePathname or other hooks

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/*  if ('serviceWorker' in navigator) {

// Регистрируем сервисный рабочий процесс

navigator.serviceWorker.register('/notificationapi-service-worker.js')

.then(function(registration) {

console.log('Сервисный рабочий процесс зарегистрирован с областью:', registration.scope);

})

.catch(function(error) {

console.error('Ошибка при регистрации сервисного рабочего процесса:', error);

});

}*/

/* For dynamic routing of pages, maybe we can use this array of links
const links = [
  {
    name: "Diary",
    href: "/diary",
  },
  {
    name: "Login",
    href: "/login",
  },
  {
    name: "Sign Up",
    href: "/register",
  },
  {
    name: "Create",
    href: "/diary/create",
  },
  {
    name: "Settings",
    href: "/settings",
  },
  {
    name: "Home",
    href: "/",
  }
];
*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // You can add global providers here if needed using usepathname or other hooks
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
